<?php

namespace AdvertisingBundle\Repository;

/**
 * AdvertisingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisingRepository extends \Doctrine\ORM\EntityRepository
{
}
